neuralnet/bert_classifier/urls.py
from django.urls import path
from . import views


app_name = 'bert_classifier'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:task_id>/', views.detail, name='detail'),
    path('<int:task_id>/predict/', views.predict, name='predict'),
]

neuralnet/dialog_bot/urls.py
from django.urls import path
from . import views

app_name = 'dialog_bot'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:task_id>/', views.detail, name='detail'),
    path('<int:task_id>/predict/', views.predict, name='predict'),
]

neuralnet/neuralnet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bert_classifier/', include('bert_classifier.urls')),
    path('dialog_bot/', include('dialog_bot.urls')),
]

neuralnet/bert_classifier/models.py
from django.db import models


class Task(models.Model):
    task_name = models.CharField(max_length=50)

    def __str__(self):
        return self.task_name


class InteractionML(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    input_data = models.CharField(max_length=200)
    output_data = models.CharField(max_length=200)

    def __str__(self):
        return f"input: {self.input_data}, output:{self.output_data}"

neuralnet/dialog_bot/models.py
from django.db import models

# Create your models here.

neuralnet/bert_classifier/views.py
from django.http import HttpResponseRedirect
from .models import Task
from django.shortcuts import get_object_or_404, render
from .apps import BertClassifierConfig
from django.urls import reverse


def index(request):
    tasks_list = Task.objects.all()
    context = {'tasks_list': tasks_list}
    return render(request, 'bert_classifier/index.html', context)


def detail(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    latest_predictions = task.interactionml_set.order_by('-id')[:6][::-1]
    context = {
        'task': task,
        'latest_predictions': latest_predictions
    }
    return render(request, 'bert_classifier/detail.html', context)


def predict(request, task_id):
    task = get_object_or_404(Task, pk=task_id)

    input_text = request.POST['text']
    output = BertClassifierConfig.predictor.predict(input_text)

    task.interactionml_set.create(input_data=input_text, output_data=output)
    return HttpResponseRedirect(reverse('bert_classifier:detail', args=(task.id,)))

neuralnet/dialog_bot/views.py
from django.http import HttpResponseRedirect
from bert_classifier.models import Task
from django.shortcuts import get_object_or_404, render
from .apps import DialogBotConfig
from django.urls import reverse


def index(request):
    tasks_list = Task.objects.all()
    context = {'tasks_list': tasks_list}
    return render(request, 'dialog_bot/index.html', context)


def detail(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    latest_predictions = task.interactionml_set.order_by('-id')[:3][::-1]
    context = {
        'task': task,
        'latest_predictions': latest_predictions
    }
    return render(request, 'dialog_bot/detail.html', context)


def predict(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    input_text = request.POST['text']

    output = DialogBotConfig.dialog_bot.predict(input_text)
    task.interactionml_set.create(input_data=input_text, output_data=output)

    return HttpResponseRedirect(reverse('dialog_bot:detail', args=(task.id,)))

neuralnet/bert_classifier/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Django ML backend{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

neuralnet/bert_classifier/templates/bert_classifier/detail.html
{% extends 'base.html' %}

{% block title %}{{ task.task_name }}{% endblock %}

{% block content %}

<h2>{{task.task_name}}</h2>

<form action="{% url 'bert_classifier:index' %}" method="POST">

    {% csrf_token %}

    <button type="submit">На главную</button>

</form>

<hr>

    {% if latest_predictions %}

        {% for p in latest_predictions %}
            <p>
                <strong>{{p.input_data}}</strong>
                <pre>{{p.output_data}}</pre>
            </p>
        {% endfor %}

    {% else %}
    Нет предыдущих результатов.
    {% endif %}

</hr>

<form action="{% url 'bert_classifier:predict' task.id %}" method="POST">

    {% csrf_token %}

    <textarea name="text" required="" placeholder="Введите текст" cols="70" rows="10"></textarea><br>
    <button type="submit">Классифицировать текст</button>

</form>

{% endblock %}

neuralnet/bert_classifier/templates/bert_classifier/index.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'bert_classifier/style.css' %}">

{% if tasks_list %}
<ul>
    {% for task in tasks_list %}
        {% if task.task_name == "Text Classification" %}
            <li><a href="{% url 'bert_classifier:detail' task.id %}">{{ task.task_name }}</a></li>
        {% endif %}

    {% endfor %}
</ul>
{% else %}
<p>No tasks are available.</p>
{% endif %}

{% endblock %}

neuralnet/dialog_bot/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Django ML backend{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

neuralnet/dialog_bot/templates/dialog_bot/detail.html
{% extends 'base.html' %}

{% block title %}{{ task.task_name }}{% endblock %}
{% block content %}
    <h2>{{ task.task_name }}</h2>
    <form action="{% url 'dialog_bot:index' %}" method="POST">
        {% csrf_token %}
        <button type="submit">На главную</button>
    </form>
    <hr>
    {% if latest_predictions %}
        {% for p in latest_predictions %}
            <p>
                <strong>Вы: {{ p.input_data }}</strong>
                <p>Бот: {{ p.output_data }}</p>
            </p>
        {% endfor %}
    {% else %}
        Нет предыдущих результатов.
    {% endif %}
    </hr>
    <form action="{% url 'dialog_bot:predict' task.id %}" method="POST">
        {% csrf_token %}
        <textarea name="text" required="" placeholder="Введите текст" cols="70" rows="10"></textarea><br>
        <button type="submit">Отправить сообщение</button>
    </form>
{% endblock %}

neuralnet/dialog_bot/templates/dialog_bot/index.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
    <form action="{% url 'index' %}" method="POST">
        {% csrf_token %}
        <button type="submit">На главную</button>
    </form>
    {% if tasks_list %}
        <ul>
            {% for task in tasks_list %}
                <li><a href="{% url 'dialog_bot:detail' task.id %}">{{ task.task_name }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No tasks are available.</p>
    {% endif %}
{% endblock %}